echo "Evaluating the video: ../../videos with CUS"
echo "Epsilon:0.4"
echo "Users:5"
echo "Simple zone"
../../src/build/osm --method cus -e 0.4 -n 5 -f 3591 -r "../../output/v46/reference" -i "../../output/v46/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2118 -r "../../output/v22/reference" -i "../../output/v22/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3192 -r "../../output/v27/reference" -i "../../output/v27/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1740 -r "../../output/v55/reference" -i "../../output/v55/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2517 -r "../../output/v31/reference" -i "../../output/v31/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2618 -r "../../output/v62/reference" -i "../../output/v62/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1944 -r "../../output/v29/reference" -i "../../output/v29/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1759 -r "../../output/v23/reference" -i "../../output/v23/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3614 -r "../../output/v49/reference" -i "../../output/v49/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2689 -r "../../output/v32/reference" -i "../../output/v32/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3449 -r "../../output/v57/reference" -i "../../output/v57/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1815 -r "../../output/v24/reference" -i "../../output/v24/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2325 -r "../../output/v56/reference" -i "../../output/v56/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2739 -r "../../output/v65/reference" -i "../../output/v65/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3561 -r "../../output/v28/reference" -i "../../output/v28/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3413 -r "../../output/v37/reference" -i "../../output/v37/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 4223 -r "../../output/v36/reference" -i "../../output/v36/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 4796 -r "../../output/v43/reference" -i "../../output/v43/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 5309 -r "../../output/v64/reference" -i "../../output/v64/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2187 -r "../../output/v66/reference" -i "../../output/v66/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2765 -r "../../output/v41/reference" -i "../../output/v41/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2674 -r "../../output/v42/reference" -i "../../output/v42/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3705 -r "../../output/v48/reference" -i "../../output/v48/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2106 -r "../../output/v59/reference" -i "../../output/v59/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1797 -r "../../output/v25/reference" -i "../../output/v25/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3290 -r "../../output/v21/reference" -i "../../output/v21/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1815 -r "../../output/v30/reference" -i "../../output/v30/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 4205 -r "../../output/v34/reference" -i "../../output/v34/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2722 -r "../../output/v67/reference" -i "../../output/v67/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3616 -r "../../output/v69/reference" -i "../../output/v69/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3186 -r "../../output/v58/reference" -i "../../output/v58/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3261 -r "../../output/v33/reference" -i "../../output/v33/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 4570 -r "../../output/v38/reference" -i "../../output/v38/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2428 -r "../../output/v45/reference" -i "../../output/v45/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2275 -r "../../output/v61/reference" -i "../../output/v61/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2429 -r "../../output/v44/reference" -i "../../output/v44/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2940 -r "../../output/v40/reference" -i "../../output/v40/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2336 -r "../../output/v35/reference" -i "../../output/v35/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1949 -r "../../output/v68/reference" -i "../../output/v68/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1883 -r "../../output/v53/reference" -i "../../output/v53/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2166 -r "../../output/v47/reference" -i "../../output/v47/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 5254 -r "../../output/v39/reference" -i "../../output/v39/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2886 -r "../../output/v54/reference" -i "../../output/v54/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 1407 -r "../../output/v70/reference" -i "../../output/v70/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 3615 -r "../../output/v52/reference" -i "../../output/v52/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2310 -r "../../output/v63/reference" -i "../../output/v63/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2093 -r "../../output/v60/reference" -i "../../output/v60/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 6269 -r "../../output/v26/reference" -i "../../output/v26/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 4829 -r "../../output/v50/reference" -i "../../output/v50/data/" --verbose 
../../src/build/osm --method cus -e 0.4 -n 5 -f 2934 -r "../../output/v51/reference" -i "../../output/v51/data/" --verbose 
